#!groovy

// Generated by IBM TransformationAdvisor
// Fri Mar 01 20:13:01 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}